# Generated by Django 5.1.6 on 2025-02-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engine_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horse_power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('torque', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
