# Generated by Django 5.1.6 on 2025-02-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_car_created_at_car_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(help_text='e.g., SUV, Sedan, Hatchback', max_length=50, null=True),
        ),
    ]
