# Generated by Django 5.1.6 on 2025-02-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
