# Generated by Django 5.1.6 on 2025-02-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_car_discription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['car_model', 'variant'], 'verbose_name_plural': 'Car'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_url',
        ),
        migrations.AddField(
            model_name='car',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload an image of the car', null=True, upload_to='car_images/'),
        ),
    ]
