# Generated by Django 5.1.6 on 2025-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_car_options_remove_car_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark as featured car'),
        ),
    ]
