# Generated by Django 5.1.6 on 2025-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_car_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
