# Generated by Django 5.1.6 on 2025-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_car_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload an image of the brand', null=True, upload_to='brand_images/'),
        ),
    ]
