# Generated by Django 5.1.6 on 2025-03-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_remove_brand_image_file_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(help_text='e.g., SUV, Sedan, Hatchback', max_length=50, null=True)),
            ],
        ),
    ]
