# Generated by Django 5.1.6 on 2025-03-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_car_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='category',
            new_name='categories',
        ),
    ]
