# Generated by Django 5.1.6 on 2025-03-05 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_rename_category_car_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Petrol, Diesel, Electric, Hybrid', max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['car_model', 'variant'], 'verbose_name_plural': 'Cars'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='categories',
            new_name='body_style',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='reviews.fueltype'),
        ),
    ]
