# Generated by Django 5.1.6 on 2025-03-05 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_fueltype_alter_car_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='body_style',
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['car_model', 'variant'], 'verbose_name_plural': 'Car'},
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(help_text='e.g., SUV, Sedan, Hatchback', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
    ]
