# Generated by Django 5.1.6 on 2025-03-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_alter_category_name_alter_fueltype_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(blank=True, choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('MPV', 'MPV'), ('SUV', 'SUV')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=50, null=True),
        ),
    ]
