# Generated by Django 5.1.6 on 2025-03-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_review_user'),
        ('reviews', '0019_alter_car_body_style_alter_car_fuel_type_and_more'),
    ]

    operations = [
    ]
