# Generated by Django 5.1.6 on 2025-03-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_merge_20250306_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='body_style',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['car_model', 'variant'], 'verbose_name_plural': 'Car'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='description',
            new_name='discription',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(help_text='e.g., SUV, Sedan, Hatchback', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='variant',
            field=models.CharField(help_text='e.g., VXI, ZXI, ZXI+', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
    ]
