# Generated by Django 5.1.6 on 2025-03-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_remove_car_body_style_remove_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(max_length=20),
        ),
    ]
