# Generated by Django 5.1.6 on 2025-03-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_cargallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargallery',
            name='category',
            field=models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('gallery', 'Gallery')], default='gallery', max_length=20),
        ),
    ]
