# Generated by Django 5.1.6 on 2025-03-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_cargallery_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargallery',
            name='category',
        ),
    ]
