# Generated by Django 5.1.6 on 2025-03-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_remove_cargallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='crash_test_video',
            field=models.URLField(blank=True, help_text='YouTube link of crash test', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='safety_features',
            field=models.TextField(blank=True, help_text='Comma-separated safety features', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='safety_rating',
            field=models.FloatField(default=0.0, help_text='Safety rating out of 5'),
        ),
    ]
