# Generated by Django 5.1.6 on 2025-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0027_car_crash_test_video_car_safety_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ncap_rating',
            field=models.IntegerField(default=0, help_text='NCAP safety rating out of 5'),
        ),
    ]
