# Generated by Django 5.1.6 on 2025-03-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_car_ncap_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='safety_features',
        ),
    ]
