# Generated by Django 5.1.6 on 2025-03-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0029_remove_car_safety_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='ncap_rating',
        ),
    ]
