# Generated by Django 5.1.6 on 2025-03-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0031_car_ncap_rating_car_safety_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='ncap_rating',
        ),
        migrations.RemoveField(
            model_name='car',
            name='safety_features',
        ),
    ]
