# Generated by Django 5.1.6 on 2025-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0032_remove_car_ncap_rating_remove_car_safety_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ncap_rating',
            field=models.IntegerField(default=0, help_text='NCAP safety rating out of 5'),
        ),
    ]
