# Generated by Django 5.1.6 on 2025-03-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0033_car_ncap_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='crash_test_video',
            new_name='Car_detailed_review',
        ),
    ]
